language: node_js
node_js:
    - "8"
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
notifications:
    email: false
    webhooks:
        secure: "SHJwLfWHnL5M91w8zUk6kQKYliDfB9XutQVs/tei+N4uFjjfTD02CEIW8l34fZg2tUUyNqI12U3LHGqiBw2qwiBjsnoeSsb+4RwJsK9NQ+ie+aa6Ee6e7vZfVGlXJI0io6t240fbOt3tuQ18Q6Cv0Jsx/U/Giy1FcYYie3fauHo6KNWqoJdmrs7XSMCExYIt8noLjVscWmQOgKbXZBPrMr5N4eMo3fW6+Tr95j7+yvMu7GqHw+Xcerw7NlxqRbzv3Ry9i69jydCHL+RnF9pxh89yTNUyeak5HW7CIqi8L5nlukBPK8RMQHMqhGVY3nGvoNGrmx6otaZURRhizFudFiR3gmnFZ8BlSQADkPfFgYdGzYoiZ6aDMoznJZZtAd66E91gB2GDLPmGbQuVy59JiceO7FNmWB23fEYj16Puyk4BOFKQC57EFoRkS4mjkL7/wn24Kp3WxvjPIYQb1PMd+VbOSXaa6xWgjtOp2fqJo05OFAAd50QeB/9hqso2bUpXawe5BLBJpp+ZjODG7707QZOaKowpSwFAKs/HiW9tj77C1eapKLvUFpIPO+u2poILLaCrAjCn7OwuPW1RL+sGDJ4rf1ESPkfmhMczA7nzHm84v/tx1RsFPxztgDYOEcZbMT0b0+lin60Q6MHmBR8Bp1/mzGNOEIwDaLEb+LL0blM="
    on_success: always
    on_failure: change
    on_cancel: never
    on_error: never
