language: node_js
node_js:
    - "8"
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
notifications:
    email: false
    webhooks:
        secure: "JAlGaGl9RTVYtPWlHQ+09oypJ60tub7T66tM2Q31+R4/A0IdmSbpgGjOWX74eOTxLeM8TbsS69CSQSpxLlI9yQFdGMSvInl6bX6r1/QphqTCiE+jR64MKsb47SMaTk4Bni6mM7TJuNLuGmYBE8y+QjNK6XJzmPyvZ78StOUyNKOCz58PNAEVJN/DabW0NBLtTW1ArKHBqQrhqYJAiUrsF0Lm/mC1MLWigpLqUKTi5hWG9NYUMQqaj8arScWPUwcsp4llhr40iMtjcrTervJrYGhCg5scF9IW4DXe0xAvCEDxDjpfG7Rin/jnNvQ67+BaWL880SmX1ClRZn3j7Mc3N0xieyVwZl5JwAV45lRC+a4xeICnBREfEtJDjUqXa/4O+7ELcb8u6g12ZPSccWnHgfec9QqoSXUxzl6hI8HfAHo0o6wxynUwg/U3uigMrp452yE8oMGLNzcLZrMzd9a9SKdaou5oYxdohwlWKOcHHsLCcUmFQGCS1aY3DOuJq7DKj8kckjkT7/wbMAEAXyJkip7VI4Zdqau+ef9MNMkka0eh94VKqQJYPRpfVfTRcLv5IbdvFt/jBNQjjQ+yaExzSiMef80WgWuSLSSPC7W1po75H3pzJjYYpi93+Ki7tQ+HhIsZIodZuV/NUglITUEvvweSst4rEiKDzjReT6Bm4f0="
    on_success: always
    on_failure: change
    on_cancel: never
    on_error: never
