language: node_js
node_js:
    - "8"
notifications:
    email: false
    webhooks:
        secure: "pkKRl1cXg4SeHCwRdnJtKhmOPPvTkNo758IkVttJmBBcM+/BzxadSZWG0ZReslqExj+ejOpp/9xQbPMrF+8e4H+XS/whNhafZ2nonY8XiEp+BHqGZ9txZdnug0anS8oHQNoHIh3kiyY6D1iDrC5lYdtAwClxv6kUi45tkVArMTovX0SRzTxuYc19I3ucsIUXwcHopdQMznb9g0PMWfrU3HnSERp10t50enige4TXpP/r0tdG0vAR5erYBIi5Vz+iLYRAc/igWP7gfecr4Dy/vouFJh7V4S2KHp4qRYcl49FasckFGBqYLWjBXapBkv2CnxN+saCZTAetE4O+VepiO74Fg6rH/+G4iEMQzv7MljUx3ftbGboc0u0k/3XK68aoThguk0cN+ljcGibIq+VnE5c5UT/6RXuWRAR+lhi7d0sp6qNgTdhp5A7FH90lilqF4+IEs05t5cR0f+lA9aVqd/7zCVMzCpTduQhtVC49Ru9Q+5+Sh1/oRG8VYOLgQBbalG+y2Gl53wdNHmDb0lPDbD+/HqQL9PVqSeiDnShHZO5lvomNL7gEgI6iyZuV1Sk4WuXOzxxkIW5wryXcUyx2FKOuvUcDFHqQbKstXHvyj3IgwqMD6LLgO0A7Y0M+Yao3tDZE1X0a9bD3uzBiMNK5rvOG7WoyLTVka5WpK1NODoM="
    on_success: always
    on_failure: change
    on_cancel: never
    on_error: never