language: node_js
node_js:
    - "8"
notifications:
    email: false
    webhooks:
        secure: "eQez0FaplgAGV2pTUZGdU6RT1Jyvjn4krgvFgU/mHIyT3XmOmAVf4TtIUPJ1XPtpM5XUuyVNgOibF8dFzY1Xsl7n/Z8YCOrv8SsJdQ5r2CMRlX2eP5lSBD1M+eWy6gjQdtEwnkv4M1D6iXAXo8KTNDpKjIpMdJfUlt6rMoOf/jnrcqQxz631SkSI6ydhCJa3vilhhiFwVQFDl/2o5BY1edtBAwRcW4zGqGBIJ3jOEgRaiitfTy40gcyZBvJmxfArHt9fdEpiz1ekQEO4EWTM54igFLsEfEQt6egQLfdazRlB/S0dnvq8qNWT//5A+9SeibjXnQ1+/yJTnJmZWnwjaQcU2Hv1r0A5BJ/i05HYQ8ULtJB/YBz3TbYuHosUlbrVWek/QTXKw19gy8A60z/n+a/ZxnzqiL70YNHLauBV9Ihu/ygbLus8EVivwUOUUiVvFD4ue6SLwDWBWHCnPLw6tlt1oZ5CYTFjNsubC6Mp8KvIZ+Uy3y9X0ky9BTdjVQ2g5N0ShiyD+2pV7b6bNsn8sbaSohdrhu2RTIGS0BdriNbR0UGC9qrkZqoHEL2J2IP7VAKo7XjmsrBw9Zf4prLKL1DU1PKUZFQaxW8c6NQF8xU7WfudXIUdnUTT8w2hv2Pdx3nq0PQGs/Kcx+HGCv3xxuvKU19hrMexENYBlT778UY="
    on_success: always
    on_failure: change
    on_cancel: never
    on_error: never
